wget https://designreset.com/cork/html/src/assets/img/favicon.ico
wget https://designreset.com/cork/html/layouts/modern-light-menu/css/light/loader.css
wget https://designreset.com/cork/html/layouts/modern-light-menu/css/light/loader.css
wget https://designreset.com/cork/html/layouts/modern-light-menu/loader.js
wget https://designreset.com/cork/html/src/bootstrap/css/bootstrap.min.css
wget https://designreset.com/cork/html/layouts/modern-light-menu/css/light/plugins.css
wget https://designreset.com/cork/html/layouts/modern-light-menu/css/dark/plugins.css
wget https://designreset.com/cork/html/src/plugins/src/apex/apexcharts.css
wget https://designreset.com/cork/html/src/assets/css/light/components/list-group.css
wget https://designreset.com/cork/html/src/assets/css/light/dashboard/dash_2.css
wget https://designreset.com/cork/html/src/assets/css/dark/components/list-group.css
wget https://designreset.com/cork/html/src/assets/css/dark/dashboard/dash_2.css
wget https://designreset.com/cork/html/src/assets/img/1x1/us.svg
wget https://designreset.com/cork/html/src/assets/img/profile-16.jpeg
wget https://designreset.com/cork/html/src/assets/img/profile-15.jpeg
wget https://designreset.com/cork/html/src/assets/img/profile-21.jpeg
wget https://designreset.com/cork/html/src/assets/img/profile-30.png
wget https://designreset.com/cork/html/src/assets/img/logo.svg
wget https://designreset.com/cork/html/src/assets/img/profile-30.png
wget https://designreset.com/cork/html/src/assets/img/netflix.svg
wget https://designreset.com/cork/html/src/assets/img/apple-app-store.svg
wget https://designreset.com/cork/html/src/bootstrap/js/bootstrap.bundle.min.js
wget https://designreset.com/cork/html/src/bootstrap/js/bootstrap.bundle.min.js
wget https://designreset.com/cork/html/src/plugins/src/mousetrap/mousetrap.min.js
wget https://designreset.com/cork/html/src/plugins/src/waves/waves.min.js
wget https://designreset.com/cork/html/layouts/modern-light-menu/app.js
wget https://designreset.com/cork/html/src/plugins/src/apex/apexcharts.min.js
wget https://designreset.com/cork/html/src/assets/js/dashboard/dash_2.js
