<script src="{{URL::asset('/rapidev_erp_jquery_v1/jquery-3.2.1.min.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/jquery-ui.min.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/alasql/dist/alasql.min.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/clusterisejs/clusterize.min.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/adddeleteupdate2.js')}}"></script>
<!-- <script src="{{URL::asset('/rapidev_erp_jquery_v1/toast/dist/jquery.toast.min.js')}}"></script> -->
<script src="{{URL::asset('/rapidev_erp_jquery_v1/ajaxrequests.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/formsearch2.0.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/main.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/tablesearch2.0.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/erpcustom_autocomplete.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/erpplus_jquery_library.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/mustache.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/fixedtableheader/tableHeadFixer.js')}}"></script>
<script src="{{URL::asset('/rapidev_erp_jquery_v1/sweetalert2.min.js')}}"></script>